[versions]
leavesApi = "1.21.10-R0.1-SNAPSHOT"
leavesweightUserdev = "2.1.0-SNAPSHOT"
shadow = "9.0.0-rc1"
runPaper = "2.3.1"
resourceFactory = "1.0.0"

[libraries]
leavesApi = { group = "org.leavesmc.leaves", name = "leaves-api", version.ref = "leavesApi" }
leavesDevBundle = { group = "org.leavesmc.leaves", name = "dev-bundle", version.ref = "leavesApi" }

[plugins]
leavesweightUserdev = { id = "org.leavesmc.leavesweight.userdev", version.ref = "leavesweightUserdev" }
shadowJar = { id = "com.gradleup.shadow", version.ref = "shadow" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
resourceFactory = { id = "org.leavesmc.resource-factory", version.ref = "resourceFactory" }